#!/bin/bash

# Get the local configuration.
source ~/.gitbackup

# Make sure that the correct variables are set!
# http://stackoverflow.com/a/13864829
if [ -z ${PASSPHRASE+x} ]; then
    echo "You must configure an encryption password!"
    exit 1
fi

if [[ ${#REPOS[@]} -lt 1 ]]; then
    echo "You must specify at least one repository to backup!"
    exit 1
fi

if [[ -z "$BUCKET" ]]; then
    echo "You must specify an s3 bucket for uploading!"
    exit 1
fi

# Make sure that cfv is installed.
command -v cfv >/dev/null 2>&1 || { \
    echo >&2 "Cfv is not installed. Aborting!"; exit 1; \
}

# Make sure s3cmd is installed.
command -v s3cmd >/dev/null 2>&1 || { \
    echo >&2 "S3cmd is not installed. Aborting!"; exit 1; \
}

# Make sure s3cmd has been configured.
if [ ! -f ~/.s3cfg ]; then
    echo >&2 "S3cmd has not been configured yet. Aborting!"
    exit 1
fi

for repo_url in "${REPOS[@]}"; do
    filename=$(basename $repo_url)
    repo="${filename%.*}"
    parent="${repo_url%/*}"
    project="${parent##*:}"

    mkdir -vp "$project"
    cd "$project"

    # http://stackoverflow.com/a/3960063
    git clone --mirror "$repo_url"

    cd ../
done

for project_dir in */; do
    cd "$project_dir"

    # http://serverfault.com/a/303400
    cfv -C -rr -t sha1

    cd ../
    tar -czvf "${repo_dir%/}.tgz" "$repo_dir"
done

for repo_tar in *.tgz; do
    gpg --cipher-algo AES256 --symmetric --yes --batch \
        --passphrase="$PASSPHRASE" "$repo_tar"
done
